[[CUDNN_CUDA102]]
arch = "x86_64"
git-tree-sha1 = "fc5abe954be532ce9bf6882b3cfb906a880e33e3"
libc = "glibc"
os = "linux"

    [[CUDNN_CUDA102.download]]
    sha256 = "5130ea7495e2d20e1c9894460fa6b2cca623b8ab5aadeb1e144326e416345bbd"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_CUDA102_jll.jl/releases/download/CUDNN_CUDA102-v8.1.0+0/CUDNN_CUDA102.v8.1.0.x86_64-linux-gnu.tar.gz"
[[CUDNN_CUDA102]]
arch = "x86_64"
git-tree-sha1 = "4dfab62984ed08dc96d08d92d328cb7a0ded0bb2"
os = "windows"

    [[CUDNN_CUDA102.download]]
    sha256 = "3ae0ae5feb75ac26a7a35d40800af3384ee6ccae45fd74d66a004e6d1cee39ca"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_CUDA102_jll.jl/releases/download/CUDNN_CUDA102-v8.1.0+0/CUDNN_CUDA102.v8.1.0.x86_64-w64-mingw32.tar.gz"
