[[CUDNN_CUDA102]]
arch = "x86_64"
git-tree-sha1 = "85541be8da184b27fcca8772fa6989008fa76c72"
libc = "glibc"
os = "linux"

    [[CUDNN_CUDA102.download]]
    sha256 = "ae85091dafd20e4f070148825d247a9a3ab8066888833e88b01a3d30571954f5"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_CUDA102_jll.jl/releases/download/CUDNN_CUDA102-v8.0.4+0/CUDNN_CUDA102.v8.0.4.x86_64-linux-gnu.tar.gz"
[[CUDNN_CUDA102]]
arch = "powerpc64le"
git-tree-sha1 = "bc48bc3f534400aa4a841fa5886f794ee458d380"
libc = "glibc"
os = "linux"

    [[CUDNN_CUDA102.download]]
    sha256 = "83fdecd9b53c83f4b024beb24cf93a755b6a5a53011d4783e8bf06cadee47ffe"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_CUDA102_jll.jl/releases/download/CUDNN_CUDA102-v8.0.4+0/CUDNN_CUDA102.v8.0.4.powerpc64le-linux-gnu.tar.gz"
[[CUDNN_CUDA102]]
arch = "x86_64"
git-tree-sha1 = "d1e2f396182c9319f1ae2e7f020a3b969ccb8cc6"
os = "windows"

    [[CUDNN_CUDA102.download]]
    sha256 = "be6a8c9892bd397ab055eec3ccffcf8e706ea8e2f0e4b49223eba895b38d2fe1"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_CUDA102_jll.jl/releases/download/CUDNN_CUDA102-v8.0.4+0/CUDNN_CUDA102.v8.0.4.x86_64-w64-mingw32.tar.gz"
